spring:
  h2.console:
    enabled: true
    path: /h2-console

  datasource:
    url: jdbc:h2:~/test
    driverClassName: org.h2.Driver
    username: sa
    password:

chaosServer:
  #googleClientId: 580716329785-9miqrpmo48m5cu1uqabtigvgpna0m512.apps.googleusercontent.com
  googleClientId: 407408718192.apps.googleusercontent.com
#logging.level.io.ebean.SQL: TRACE
#logging.level.io.ebean.TXN: TRACE
#logging.level.io.ebean.SUM: TRACE