logging:
  level.org.springframework: TRACE

chaosServer:
  googleClientId: 407408718192.apps.googleusercontent.com
  #googleClientId: 580716329785-9miqrpmo48m5cu1uqabtigvgpna0m512.apps.googleusercontent.com