spring:
  profiles.active: dev

logging:
  level.org.springframework: TRACE

server:
  port: 8443
  ssl:
    key-store: classpath:keystore.jks
    key-store-type: JKS
    key-store-password: chaos42
    key-alias: selfsigned

security.require-ssl: true

chaosServer:
  googleClientId: 407408718192.apps.googleusercontent.com
  #googleClientId: 580716329785-9miqrpmo48m5cu1uqabtigvgpna0m512.apps.googleusercontent.com